### ISSUE TITLE
Enable for mobile?

### ISSUE THREAD

**Issue by treyharris** [bicarlsen/obsidian_html_tags_autocomplete#3]
https://github.com/bicarlsen/obsidian_html_tags_autocomplete/blob/c6bb2dca22759c318a9921ceabfcc9e809e30ce5/manifest.json#L9

I’ve had a look at the code and I don’t immediately see where `"isDesktopOnly": true` is necessary. If it isn’t, could you change it to `false`? I would like to use it on my iPad. Thanks!

**Comment by bicarlsen** [comment]
I think the reason I set it to dekstop only is because I don't have a mobile device to test it on. If it's possible for you to test it yourself, perhaps you could give it a shot and see if it works before I release a new version with it enabled.

**Comment by bicarlsen** [comment]
This is now included in [version 0.0.6](https://github.com/bicarlsen/obsidian_html_tags_autocomplete/releases/tag/0.0.6).
