### ISSUE TITLE
Is it possible to disable for certain tag?

### ISSUE THREAD

**Issue by yann5280** [bicarlsen/obsidian_html_tags_autocomplete#7]
For example <br>, it's is no needed to have a closing tag.

**Comment by yann5280** [comment]
add these lines into editor_suggest.ts
(after line 32)
```
// Self-closing tags list
    const NOCLOSING = ["br", "hr"];
    if (NOCLOSING.includes(cursor_tag[2])) {
      return null;
    }
```

**Comment by bicarlsen** [comment]
I no longer use Obsidian, so if you could test out the new version on branch `feat-self_closing_tags` and let me know if it works or not, I would greatly appreciate it.

**Comment by yann5280** [comment]
Sorry that I don't know how to compile them into packed `main.js`.
So I tried to add it directly into the `main.js`. And yeah, it works.
<img width="220" alt="image" src="https://user-images.githubusercontent.com/71702628/233832448-fbf4abb7-8652-4621-86fc-80457ddc4c92.png">
<img width="219" alt="image" src="https://user-images.githubusercontent.com/71702628/233832467-fe651820-f6f9-4d54-bfaa-319049c6e6bf.png">
It no longer suggests a closing </br> compared to the previous version, without affecting the other tags.

**Comment by bicarlsen** [comment]
This has been incorporated into release 0.0.7. Please give it a try and let me know if there are any issues. If everything works you can close the issue.

**Comment by FAL0258** [comment]
Thanks, it works.
